services:
  - type: web
    name: qb-recharge
    runtime: python
    plan: free
    buildCommand: echo "no build"
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.7"
